// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200310162355_PersonelEntityAdded")]
    partial class PersonelEntityAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Domain.Personal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("arb_status")
                        .HasColumnType("TEXT");

                    b.Property<string>("brukerkonto")
                        .HasColumnType("TEXT");

                    b.Property<string>("epost")
                        .HasColumnType("TEXT");

                    b.Property<string>("etternavn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fodselsdato")
                        .HasColumnType("TEXT");

                    b.Property<string>("fornavn")
                        .HasColumnType("TEXT");

                    b.Property<string>("gateadresse")
                        .HasColumnType("TEXT");

                    b.Property<string>("kjonn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("opprettet")
                        .HasColumnType("TEXT");

                    b.Property<string>("postnummerid")
                        .HasColumnType("TEXT");

                    b.Property<string>("telefon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personal");
                });

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Value 101"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Value 102"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Value 103"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
